tap "atomicjar/tap"
tap "dopplerhq/cli"
tap "fluxcd/tap"
tap "go-task/tap"
tap "int128/kubelogin"
tap "jesseduffield/lazydocker"
tap "jesseduffield/lazygit"
tap "jrockway/tap"
tap "kyu08/tap"
tap "martido/graph"
tap "mikescher/tap"
tap "oven-sh/bun"
tap "spacelift-io/spacelift"
tap "superfly/tap"
brew "act"
brew "age"
brew "ast-grep"
brew "sqlite"
brew "awscli"
brew "bat"
brew "black"
brew "openjdk"
brew "bundletool"
brew "ruby", link: true
brew "cocoapods"
brew "coreutils"
brew "deno"
brew "direnv"
brew "eksctl"
brew "entr"
brew "exercism"
brew "eza"
brew "fzf"
brew "gh"
brew "git"
brew "git-interactive-rebase-tool"
brew "git-recent"
brew "git-standup"
brew "git-town"
brew "gitlab-runner"
brew "glab"
brew "gnuplot"
brew "golangci-lint-langserver"
brew "graphviz"
brew "helix"
brew "helm"
brew "htop"
brew "hyperfine"
brew "jj"
brew "jq"
brew "just"
brew "k9s"
brew "kafka"
brew "kubeconform"
brew "kubernetes-cli"
brew "kubectx"
brew "kustomize"
brew "kyverno"
brew "lazygit"
brew "libimobiledevice"
brew "mas"
brew "mise"
brew "mkcert"
brew "mprocs"
brew "mpv"
brew "ncspot"
brew "node"
brew "nss"
brew "opentofu"
brew "p7zip"
brew "pipx"
brew "pkgconf"
brew "postgresql@14", restart_service: :changed
brew "pre-commit"
brew "prettyping"
brew "procs"
brew "pstree"
brew "redis", restart_service: :changed
brew "rename"
brew "rust"
brew "showkey"
brew "sops"
brew "stern"
brew "stow"
brew "svgo"
brew "tektoncd-cli"
brew "terraform"
brew "terraform-docs"
brew "tflint"
brew "the_silver_searcher"
brew "tree"
brew "typescript"
brew "typescript-language-server"
brew "vale"
brew "vscode-langservers-extracted"
brew "xcodegen"
brew "yarn"
brew "yq"
brew "zx"
brew "dopplerhq/cli/doppler"
brew "fluxcd/tap/flux", link: false
brew "int128/kubelogin/kubelogin"
brew "jesseduffield/lazydocker/lazydocker"
brew "jrockway/tap/kubectl-jq"
brew "mikescher/tap/dops"
brew "spacelift-io/spacelift/spacectl"
cask "1password-cli"
cask "aerial"
cask "appcleaner"
cask "couleurs"
cask "docker-desktop"
cask "figma"
cask "flutter"
cask "flux-app"
cask "font-commit-mono"
cask "font-jetbrains-maple-mono-nf"
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspace"
cask "font-patrick-hand"
cask "font-patrick-hand-sc"
cask "font-victor-mono"
cask "github"
cask "gitup-app"
cask "gpg-suite"
cask "iterm2"
cask "jordanbaird-ice"
cask "kaleidoscope@3"
cask "kap"
cask "latest"
cask "logi-options+"
cask "logitune"
cask "maccy"
cask "macdown"
cask "postico"
cask "postman"
cask "rectangle"
cask "runjs"
cask "signal"
cask "sourcetree"
cask "spotify"
cask "stats"
cask "tempbox"
cask "atomicjar/tap/testcontainers-desktop"
cask "textexpander"
cask "tuple"
cask "vscodium"
cask "warp"
cask "wave"
cask "wezterm"
cask "zed"
mas "1Password for Safari", id: 1569813296
mas "Actions", id: 1586435171
mas "Aeroplan Shopping Button", id: 6443815835
mas "Amphetamine", id: 937984704
mas "Be Focused Pro", id: 961632517
mas "Capo", id: 696977615
mas "DaisyDisk", id: 411643860
mas "Focus Matrix", id: 1087284172
mas "GarageBand", id: 682658836
mas "Hand Mirror", id: 1502839586
mas "Icon Fun", id: 1202847196
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Mactracker", id: 430255202
mas "MindNode Next", id: 6446116532
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Okta Verify", id: 490179405
mas "One Task", id: 6465745322
mas "Pages", id: 409201541
mas "Refined GitHub", id: 1519867270
mas "Sequel Ace", id: 1518036000
mas "Tomito", id: 1526042938
mas "Unsplash Wallpapers", id: 1284863847
vscode "akamud.vscode-theme-onelight"
vscode "antfu.unocss"
vscode "anysphere.cursorpyright"
vscode "anysphere.remote-ssh"
vscode "arcanis.vscode-zipfs"
vscode "ast-grep.ast-grep-vscode"
vscode "astro-build.astro-vscode"
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "buenon.scratchpads"
vscode "clinyong.vscode-css-modules"
vscode "dbaeumer.vscode-eslint"
vscode "denoland.vscode-deno"
vscode "dracula-theme.theme-dracula"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "firsttris.vscode-jest-runner"
vscode "formulahendry.auto-rename-tag"
vscode "github.github-vscode-theme"
vscode "github.vscode-pull-request-github"
vscode "gitlab.gitlab-workflow"
vscode "golang.go"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-syntax"
vscode "gruntfuggly.todo-tree"
vscode "hashicorp.terraform"
vscode "hverlin.mise-vscode"
vscode "jnoortheen.nix-ide"
vscode "k--kato.intellij-idea-keybindings"
vscode "mhutchie.git-graph"
vscode "mkhl.direnv"
vscode "mrmlnc.vscode-scss"
vscode "ms-playwright.playwright"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode.makefile-tools"
vscode "nrwl.angular-console"
vscode "orta.vscode-jest"
vscode "phoenisx.cssvar"
vscode "prisma.prisma"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "rvest.vs-code-prettier-eslint"
vscode "sdras.night-owl"
vscode "serayuzgur.crates"
vscode "stylelint.vscode-stylelint"
vscode "svelte.svelte-vscode"
vscode "tamasfe.even-better-toml"
vscode "tauri-apps.tauri-vscode"
vscode "unifiedjs.vscode-mdx"
vscode "usernamehw.errorlens"
vscode "viijay-kr.react-ts-css"
vscode "visualjj.visualjj"
vscode "vitest.explorer"
vscode "yoavbls.pretty-ts-errors"
vscode "zhuangtongfa.material-theme"
cargo "bacon"
cargo "cargo-deny"
cargo "cargo-expand"
cargo "cargo-llvm-cov"
cargo "cargo-nextest"
cargo "cargo-watch"
cargo "mdbook"
cargo "ripgrep"
cargo "rustlings"
cargo "top-type-sizes"
cargo "typeshare-cli"
cargo "wasm-bindgen-cli"
cargo "wasm-pack"
