tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "martido/graph"
tap "shopify/shopify"
brew "ack"
brew "openssl@1.1"
brew "automake"
brew "bat"
brew "bison"
brew "bit-git"
brew "gdbm"
brew "libffi"
brew "readline"
brew "ccat"
brew "cloc"
brew "coreutils"
brew "diff-so-fancy"
brew "docker"
brew "entr"
brew "exa"
brew "exercism"
brew "fd"
brew "libsodium"
brew "ffmpeg"
brew "foreman"
brew "fzy"
brew "gh"
brew "git"
brew "git-lfs"
brew "git-recent"
brew "git-standup"
brew "git-town"
brew "gnupg"
brew "graphviz"
brew "hub"
brew "imagemagick@6", link: true
brew "less"
brew "libgda"
brew "libyaml"
brew "markdownlint-cli"
brew "mysql-client@5.7", link: true
brew "openjdk"
brew "overmind"
brew "pinentry-mac"
brew "postgresql@11"
brew "pre-commit"
brew "prettyping"
brew "procs"
brew "python@3.8"
brew "ruby"
brew "shared-mime-info"
brew "subversion"
brew "svgo"
brew "tldr"
brew "tree"
brew "watchman"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "zsh-autosuggestions"
brew "shopify/shopify/secret-sender"
cask "appcleaner"
# cask "cakebrew"
# cask "discord"
# cask "firefox-developer-edition"
cask "fluor"
# cask "font-fira-code"
# cask "font-fira-mono-for-powerline"
# cask "font-inconsolata"
# cask "github"
cask "gitup"
cask "google-cloud-sdk"
cask "insomnia"
# cask "keybase"
# cask "kitematic"
cask "maccy"
# cask "mongodb-compass"
# cask "monitorcontrol"
cask "mpv"
cask "ngrok"
# cask "novabench"
# cask "phantomjs"
# cask "postman"
cask "rectangle"
# cask "responsively"
cask "runjs"
cask "sourcetree"
cask "spotify"
# cask "stats"
# cask "visual-studio-code"
